###PING ROUTE
GET http://localhost:3000/ping

###CREATE A NEW USER
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Sherin",
  "lastName": "Binu",
  "phone": "+919894528840",
  "password": "thisIsAPassword",
  "tosAgreement": true
}

###GET AN EXISTING USER
GET http://localhost:3000/users?phone=%2B919894528840

###UPDATE AN EXISTING USER
PUT http://localhost:3000/users
Content-Type: application/json

{
}

###DELETES AND EXISTING USER
DELETE http://localhost:3000/users?phone=%2B919894528840